name: buzz_booster_example
description: Demonstrates how to use the buzz_booster plugin.
version: 4.6.52
publish_to: 'none'

environment:
  sdk: ">=2.12.3"
  flutter: ">=2.0.6"

dependencies:
  flutter:
    sdk: flutter

  buzz_booster:
    path: ../

  cupertino_icons: 1.0.2
  firebase_messaging: 11.4.4
  firebase_core: 1.19.1
  fluttertoast: 8.0.9
  shared_preferences: 2.0.15
  flutter_phoenix: 1.0.0
  http: 0.13.5
  pubspec_parse: 1.2.1
  webview_flutter: 3.0.4
  permission_handler: 10.4.3
  sentry_flutter: 6.9.0
  sentry: 6.9.0
  
dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - ./pubspec.yaml
